package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLASS.
 */
public class Class {

    private Long ClassID;
    private Integer GradeID;
    private String ClassCode;
    private String ClassName;
    private String Remark1;

    public Class() {
    }

    public Class(Long ClassID) {
        this.ClassID = ClassID;
    }

    public Class(Long ClassID, Integer GradeID, String ClassCode, String ClassName, String Remark1) {
        this.ClassID = ClassID;
        this.GradeID = GradeID;
        this.ClassCode = ClassCode;
        this.ClassName = ClassName;
        this.Remark1 = Remark1;
    }

    public Long getClassID() {
        return ClassID;
    }

    public void setClassID(Long ClassID) {
        this.ClassID = ClassID;
    }

    public Integer getGradeID() {
        return GradeID;
    }

    public void setGradeID(Integer GradeID) {
        this.GradeID = GradeID;
    }

    public String getClassCode() {
        return ClassCode;
    }

    public void setClassCode(String ClassCode) {
        this.ClassCode = ClassCode;
    }

    public String getClassName() {
        return ClassName;
    }

    public void setClassName(String ClassName) {
        this.ClassName = ClassName;
    }

    public String getRemark1() {
        return Remark1;
    }

    public void setRemark1(String Remark1) {
        this.Remark1 = Remark1;
    }

}
