package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ROUND_RESULT.
 */
public class RoundResult {

    private Long RoundResultID;
    private Integer StudentItemID;
    private Integer Result;
    private Integer RoundNo;
    private String TestTime;
    private Integer ResultState;
    private Integer IsLastResult;
    private String Remark1;
    private String Remark2;
    private String Remark3;

    public RoundResult() {
    }

    public RoundResult(Long RoundResultID) {
        this.RoundResultID = RoundResultID;
    }

    public RoundResult(Long RoundResultID, Integer StudentItemID, Integer Result, Integer RoundNo, String TestTime, Integer ResultState, Integer IsLastResult, String Remark1, String Remark2, String Remark3) {
        this.RoundResultID = RoundResultID;
        this.StudentItemID = StudentItemID;
        this.Result = Result;
        this.RoundNo = RoundNo;
        this.TestTime = TestTime;
        this.ResultState = ResultState;
        this.IsLastResult = IsLastResult;
        this.Remark1 = Remark1;
        this.Remark2 = Remark2;
        this.Remark3 = Remark3;
    }

    public Long getRoundResultID() {
        return RoundResultID;
    }

    public void setRoundResultID(Long RoundResultID) {
        this.RoundResultID = RoundResultID;
    }

    public Integer getStudentItemID() {
        return StudentItemID;
    }

    public void setStudentItemID(Integer StudentItemID) {
        this.StudentItemID = StudentItemID;
    }

    public Integer getResult() {
        return Result;
    }

    public void setResult(Integer Result) {
        this.Result = Result;
    }

    public Integer getRoundNo() {
        return RoundNo;
    }

    public void setRoundNo(Integer RoundNo) {
        this.RoundNo = RoundNo;
    }

    public String getTestTime() {
        return TestTime;
    }

    public void setTestTime(String TestTime) {
        this.TestTime = TestTime;
    }

    public Integer getResultState() {
        return ResultState;
    }

    public void setResultState(Integer ResultState) {
        this.ResultState = ResultState;
    }

    public Integer getIsLastResult() {
        return IsLastResult;
    }

    public void setIsLastResult(Integer IsLastResult) {
        this.IsLastResult = IsLastResult;
    }

    public String getRemark1() {
        return Remark1;
    }

    public void setRemark1(String Remark1) {
        this.Remark1 = Remark1;
    }

    public String getRemark2() {
        return Remark2;
    }

    public void setRemark2(String Remark2) {
        this.Remark2 = Remark2;
    }

    public String getRemark3() {
        return Remark3;
    }

    public void setRemark3(String Remark3) {
        this.Remark3 = Remark3;
    }

}
