package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT_ITEM.
 */
public class StudentItem {

    private Long StudentItemID;
    private Integer StudentID;
    private Integer ItemID;
    private Integer LastResult;
    private Integer ResultState;
    private String LastTestTime;
    private Integer TestState;
    private String Remark1;
    private String Remark2;
    private String Remark3;

    public StudentItem() {
    }

    public StudentItem(Long StudentItemID) {
        this.StudentItemID = StudentItemID;
    }

    public StudentItem(Long StudentItemID, Integer StudentID, Integer ItemID, Integer LastResult, Integer ResultState, String LastTestTime, Integer TestState, String Remark1, String Remark2, String Remark3) {
        this.StudentItemID = StudentItemID;
        this.StudentID = StudentID;
        this.ItemID = ItemID;
        this.LastResult = LastResult;
        this.ResultState = ResultState;
        this.LastTestTime = LastTestTime;
        this.TestState = TestState;
        this.Remark1 = Remark1;
        this.Remark2 = Remark2;
        this.Remark3 = Remark3;
    }

    public Long getStudentItemID() {
        return StudentItemID;
    }

    public void setStudentItemID(Long StudentItemID) {
        this.StudentItemID = StudentItemID;
    }

    public Integer getStudentID() {
        return StudentID;
    }

    public void setStudentID(Integer StudentID) {
        this.StudentID = StudentID;
    }

    public Integer getItemID() {
        return ItemID;
    }

    public void setItemID(Integer ItemID) {
        this.ItemID = ItemID;
    }

    public Integer getLastResult() {
        return LastResult;
    }

    public void setLastResult(Integer LastResult) {
        this.LastResult = LastResult;
    }

    public Integer getResultState() {
        return ResultState;
    }

    public void setResultState(Integer ResultState) {
        this.ResultState = ResultState;
    }

    public String getLastTestTime() {
        return LastTestTime;
    }

    public void setLastTestTime(String LastTestTime) {
        this.LastTestTime = LastTestTime;
    }

    public Integer getTestState() {
        return TestState;
    }

    public void setTestState(Integer TestState) {
        this.TestState = TestState;
    }

    public String getRemark1() {
        return Remark1;
    }

    public void setRemark1(String Remark1) {
        this.Remark1 = Remark1;
    }

    public String getRemark2() {
        return Remark2;
    }

    public void setRemark2(String Remark2) {
        this.Remark2 = Remark2;
    }

    public String getRemark3() {
        return Remark3;
    }

    public void setRemark3(String Remark3) {
        this.Remark3 = Remark3;
    }

}
