package de.greenrobot.daoexample;

import de.greenrobot.daoexample.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT.
 */
public class Student {

    private Long StudentID;
    private String StudentCode;
    private String StudentName;
    private Integer Sex;
    private Integer ClassID;
    private Integer GradeID;
    private String IDCardNo;
    private String ICCardNo;
    private String DownloadTime;
    private String Remark1;
    private String Remark2;
    private String Remark3;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient StudentDao myDao;

    private StudentItem studentItem;
    private Long studentItem__resolvedKey;


    public Student() {
    }

    public Student(Long StudentID) {
        this.StudentID = StudentID;
    }

    public Student(Long StudentID, String StudentCode, String StudentName, Integer Sex, Integer ClassID, Integer GradeID, String IDCardNo, String ICCardNo, String DownloadTime, String Remark1, String Remark2, String Remark3) {
        this.StudentID = StudentID;
        this.StudentCode = StudentCode;
        this.StudentName = StudentName;
        this.Sex = Sex;
        this.ClassID = ClassID;
        this.GradeID = GradeID;
        this.IDCardNo = IDCardNo;
        this.ICCardNo = ICCardNo;
        this.DownloadTime = DownloadTime;
        this.Remark1 = Remark1;
        this.Remark2 = Remark2;
        this.Remark3 = Remark3;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getStudentDao() : null;
    }

    public Long getStudentID() {
        return StudentID;
    }

    public void setStudentID(Long StudentID) {
        this.StudentID = StudentID;
    }

    public String getStudentCode() {
        return StudentCode;
    }

    public void setStudentCode(String StudentCode) {
        this.StudentCode = StudentCode;
    }

    public String getStudentName() {
        return StudentName;
    }

    public void setStudentName(String StudentName) {
        this.StudentName = StudentName;
    }

    public Integer getSex() {
        return Sex;
    }

    public void setSex(Integer Sex) {
        this.Sex = Sex;
    }

    public Integer getClassID() {
        return ClassID;
    }

    public void setClassID(Integer ClassID) {
        this.ClassID = ClassID;
    }

    public Integer getGradeID() {
        return GradeID;
    }

    public void setGradeID(Integer GradeID) {
        this.GradeID = GradeID;
    }

    public String getIDCardNo() {
        return IDCardNo;
    }

    public void setIDCardNo(String IDCardNo) {
        this.IDCardNo = IDCardNo;
    }

    public String getICCardNo() {
        return ICCardNo;
    }

    public void setICCardNo(String ICCardNo) {
        this.ICCardNo = ICCardNo;
    }

    public String getDownloadTime() {
        return DownloadTime;
    }

    public void setDownloadTime(String DownloadTime) {
        this.DownloadTime = DownloadTime;
    }

    public String getRemark1() {
        return Remark1;
    }

    public void setRemark1(String Remark1) {
        this.Remark1 = Remark1;
    }

    public String getRemark2() {
        return Remark2;
    }

    public void setRemark2(String Remark2) {
        this.Remark2 = Remark2;
    }

    public String getRemark3() {
        return Remark3;
    }

    public void setRemark3(String Remark3) {
        this.Remark3 = Remark3;
    }

    /** To-one relationship, resolved on first access. */
    public StudentItem getStudentItem() {
        Long __key = this.StudentID;
        if (studentItem__resolvedKey == null || !studentItem__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            StudentItemDao targetDao = daoSession.getStudentItemDao();
            StudentItem studentItemNew = targetDao.load(__key);
            synchronized (this) {
                studentItem = studentItemNew;
            	studentItem__resolvedKey = __key;
            }
        }
        return studentItem;
    }

    public void setStudentItem(StudentItem studentItem) {
        synchronized (this) {
            this.studentItem = studentItem;
            StudentID = studentItem == null ? null : studentItem.getStudentItemID();
            studentItem__resolvedKey = StudentID;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
